spring.datasource.url=jdbc:postgresql://localhost:5432/pizzeria_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=8080
spring.application.name=SpringDataJpa
client.service.url=http://localhost:8081
order.service.url=http://localhost:8082
kitchen.service.url=http://localhost:8083

logging.level.org.springframework.security=DEBUG
logging.level.org.flywaydb=DEBUG


# Настройки кухни
kitchen.capacity=1
kitchen.timeout=10000

#меню пицц
pizza.margarita.name=Margarita
pizza.margarita.price.small=100
pizza.margarita.price.medium=200
pizza.margarita.price.large=300